services:

  bug-test-project:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: fixops-test-app

    restart: unless-stopped

    ports:
      - "8000:8000"

    # Метаданные для FixOps.
    labels:
      # FixOps должен отслеживать этот контейнер
      fixops.enabled: "true"

      # Название проекта
      fixops.project: "test"

      # Путь к исходному Git-репозиторию
      # внутри контейнера FixOps
      fixops.project_path: "/projects/test"
